# Generated by Django 5.2.8 on 2025-11-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
