# Generated by Django 5.2.8 on 2025-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscae_app', '0002_customuser_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
